# docker-compose.yml
version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=criptoexchanges_db
     - POSTGRES_USER=critouser
     - POSTGRES_PASSWORD=criptoclave
    ports:
      - '5432:5432'
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"